name: Deploy backend to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build and Deploy backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '21'
        
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./demo-deploy

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./demo-deploy/target/demo-deploy-0.0.1-SNAPSHOT.jar"
          target: "~/"

      - name: SSH and Run jar on EC2
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            echo "Killing old backend app if running..."
            PID=$(pgrep -f 'demo-deploy-0.0.1-SNAPSHOT.jar')

            if [ -n "$PID" ]; then # Check if PID is not empty (process was found)
              echo "Found running JAR process with PID: $PID. Killing it gracefully..."
              # Attempt to kill gracefully, using '|| true' to prevent 'set -e' from failing the script
              # if 'kill' itself returns non-zero (e.g., if the process just died).
              kill "$PID" || true
              
              # Give it a moment to shut down cleanly
              sleep 5
              
              # Check if the process is still running after the graceful kill
              if pgrep -f 'demo-deploy-00.1-SNAPSHOT.jar' > /dev/null; then
                  echo "Process still running after graceful kill. Forcing shutdown (kill -9)."
                  # Force kill if necessary, again with '|| true'
                  kill -9 "$PID" || true
              fi
              echo "Old backend app killed successfully."
            else
              echo "No old backend app found running. Continuing."
            fi

            echo "Running new backend app..."
            nohup /usr/bin/java -jar ~/demo-deploy-0.0.1-SNAPSHOT.jar > ~/backend.log 2>&1 &

            # --- IMPORTANT ---
            # Add 'true' as the last command in this script block.
            true 


